mittwald/flow

- .pnp.cjs
- package.json
- packages/components/src/components/Button/index.ts
- packages/components/src/components/Content/index.ts
- packages/components/src/components/Icon/index.ts
- packages/components/src/components/Label/index.ts
- packages/components/src/components/Navigation/Navigation.tsx
- packages/components/src/components/Navigation/components/NavigationItem/index.ts
- packages/components/src/components/Navigation/index.ts
- packages/components/src/components/RadioGroup/components/Radio/index.ts
- packages/components/src/components/RadioGroup/index.ts
- packages/components/src/components/Text/index.ts
- packages/components/vite.build.config.ts
- yarn.lock
See also https://github.com/mittwald/flow/issues/76
> Fix compiling of all components

- .github/workflows/coverage-badges.yml
- .github/workflows/coverage.yml
- .github/workflows/publish-docs.yml
- .github/workflows/publish-review-docs.yml
- .github/workflows/test.yml
- nx.json
- packages/docs/next.config.js
> ci(docs): publish review docs

- packages/components/src/components/Button/Button.module.scss
> fix(Button): fix spacing in button inside button group

- .github/workflows/publish-docs.yml
replaces https://github.com/mittwald/flow/pull/274
> chore(deps): bump actions/configure-pages from 4 to 5

- .pnp.cjs
- packages/components/.storybook/main.ts
- packages/components/package.json
- yarn.lock
> chore(Storybook): add rtl addon

- packages/docs/src/content/03-components/actions/button/guidelines.mdx
- Moved introductional text to "Grundlagen"
- Changed Do & Dont Order
- Minor content fixes and corrections
> docs: content corrections

- packages/docs/src/content/02-foundations/content-guidelines/fehlermeldungen/index.mdx
- Fixed some logical errors and wrong examples
- Changed Do & Dont Order
- Minor content correcionts
> docs: content adjustments and corrections

- packages/components/src/components/List/List.tsx
- packages/components/src/components/List/components/Header/FilterPicker/FilterPicker.tsx
- packages/components/src/components/List/components/Header/ListFilter.ts
- packages/components/src/components/List/components/Header/ListSorting.ts
- packages/components/src/components/List/components/Header/SortingPicker/SortingPicker.tsx
- packages/components/src/components/List/components/Header/SortingPickerItem/SortingPickerItem.tsx
- packages/components/src/components/List/components/Items/ListItem/FallbackRenderer.tsx
- packages/components/src/components/List/components/Items/ListItemView.ts
- packages/components/src/components/List/components/ListLoaderAsync.ts
- packages/components/src/components/List/components/ListLoaderAsyncResource.ts
- packages/components/src/components/List/components/ListStaticData.ts
- packages/components/src/components/List/index.ts
- packages/components/src/components/List/listContext.ts
- packages/components/src/components/List/model/List.ts
- packages/components/src/components/List/model/ReactTable.ts
- packages/components/src/components/List/model/filter/Filter.ts
- packages/components/src/components/List/model/filter/types.ts
- packages/components/src/components/List/model/item/Item.ts
- packages/components/src/components/List/model/item/types.ts
- packages/components/src/components/List/model/loading/IncrementalLoader.ts
- packages/components/src/components/List/model/sorting/Sorting.ts
- packages/components/src/components/List/model/sorting/types.ts
- packages/components/src/components/List/model/types.ts
- packages/components/src/components/List/stories/Default.stories.tsx
- packages/components/src/components/List/typedList.ts
- packages/components/src/lib/types/array.ts
- packages/docs/src/content/03-components/structure/list/examples/default.tsx
> fix(List): fix multiple sorting on same prop

- packages/components/src/components/List/List.tsx
- packages/components/src/components/List/components/Header/components/ActiveFilters/ActiveFilters.tsx
- packages/components/src/components/List/components/Header/components/FilterPicker/FilterPicker.tsx
- packages/components/src/components/List/model/ReactTable.ts
- packages/components/src/components/List/model/filter/Filter.ts
- packages/components/src/components/List/model/filter/FilterValue.ts
- packages/components/src/components/List/model/filter/types.ts
- packages/components/src/components/List/model/loading/IncrementalLoader.ts
- packages/components/src/components/List/model/types.ts
- packages/components/src/components/List/setupComponents/ListFilter.ts
- packages/components/src/components/List/stories/Default.stories.tsx
- packages/components/src/components/List/typedList.test-types.tsx
- support render method for filter menu items
- support custom property filter
> Filter enhancements

- packages/components/src/components/Slider/Slider.tsx
> fix(Slider): disable focus for slider buttons

- packages/components/src/components/Accordion/Accordion.module.scss
- packages/components/src/components/Accordion/Accordion.tsx
- packages/components/src/components/Accordion/stories/Default.stories.tsx
- packages/docs/src/content/03-components/structure/accordion/examples/outlined.tsx
- packages/docs/src/content/03-components/structure/accordion/overview.mdx
> feat(Accordion): add outlined variant

- packages/components/src/components/Modal/stories/Default.stories.tsx
- packages/components/src/components/Modal/stories/EdgeCases.stories.tsx
- packages/components/src/components/OverlayTrigger/OverlayTrigger.tsx
- packages/components/src/components/Popover/Popover.tsx
- packages/components/src/lib/controller/overlay/OverlayController.ts
- packages/components/src/lib/controller/overlay/useOverlayController.ts
> feat(useOverlayController): Add onOpen and onClose callback to options

- packages/docs/src/app/_components/layout/MainNavigation/MainNavigation.tsx
> docs: add SearchField to MainNavigation

- packages/components/src/components/InlineCode/InlineCode.module.scss
- packages/components/src/components/InlineCode/InlineCode.tsx
- packages/design-tokens/src/components/inline-code.yml
- packages/docs/src/content/03-components/content/inline-code/examples/dark.tsx
- packages/docs/src/content/03-components/content/inline-code/examples/light.tsx
- packages/docs/src/content/03-components/content/inline-code/overview.mdx
> Inline code/add color variants

- packages/docs/src/lib/liveCode/components/LiveCodeEditor/LiveCodeEditor.tsx
> chore: remove semicolons at the end of livecode examples

- packages/components/src/components/Link/Link.module.scss
> fix: set link width to prevent to large clickable areas

- packages/design-tokens/src/components/button.yml
> docs: fix tokens for plain button content

- packages/components/src/components/Button/Button.module.scss
- packages/components/src/components/Button/Button.tsx
- packages/components/src/components/Button/stories/Default.stories.tsx
- packages/components/src/components/Button/stories/Variants.stories.tsx
- packages/design-tokens/src/color-aliases.yml
- packages/design-tokens/src/components/button.yml
- packages/design-tokens/src/components/checkbox.yml
- packages/design-tokens/src/components/inline-code.yml
- packages/design-tokens/src/components/link.yml
- packages/design-tokens/src/components/list.yml
- packages/design-tokens/src/components/popover.yml
- packages/design-tokens/src/components/progress-bar.yml
- packages/design-tokens/src/components/radio-group.yml
- packages/design-tokens/src/components/table.yml
- packages/design-tokens/src/components/tabs.yml
- packages/design-tokens/src/form-control.yml
- packages/design-tokens/style-dictionary.config.js
- packages/docs/src/content/03-components/actions/button/examples/dark.tsx
- packages/docs/src/content/03-components/actions/button/examples/icon-clarity-do.tsx
- packages/docs/src/content/03-components/actions/button/examples/icon-clarity-dont.tsx
- packages/docs/src/content/03-components/actions/button/examples/light.tsx
- packages/docs/src/content/03-components/actions/button/examples/variants.tsx
- packages/docs/src/content/03-components/actions/button/overview.mdx
> feat: implement outline variant for button component

- packages/docs/src/content/03-components/content/labeled-value/guidelines.mdx
Adjusted the guidelines for how many labeledvalue should be placed next to another
> docs: minor adjustments

- packages/docs/src/content/03-components/overlays/modal/examples/size.tsx
closes https://github.com/mittwald/flow/issues/816
> docs(Modal): Update Modal size examples

- packages/docs/src/content/03-components/overlays/modal/examples/size.tsx
> fix(Docs): adjust content of different modal sizes to concept

- packages/components/src/components/Modal/Modal.tsx
> style: add specific heading size for sections in modals

- packages/components/src/components/NumberField/NumberField.module.scss
> fix(NumberField): applying disabled styles when aria-disabled="false"

- packages/docs/src/content/02-foundations/structure/layout/examples/general-layout.tsx
- packages/docs/src/content/02-foundations/structure/layout/examples/mStudio-layout.tsx
- packages/docs/src/content/02-foundations/structure/layout/index.mdx
- packages/docs/src/content/02-foundations/structure/layout/overview.mdx
Closes https://github.com/mittwald/flow/issues/770
> docs(Layout): Add foundation layout docs

- packages/components/src/components/Badge/Badge.module.scss
- packages/design-tokens/src/components/badge.yml
Closes https://github.com/mittwald/flow/issues/919
> style(Badge): change badge content-colour tokens

- packages/components/src/components/ContextMenu/stories/Default.stories.tsx
- packages/components/src/styles/mixins/menuItem.scss
- packages/design-tokens/src/actions/menu-item.yml
> style(MenuItem): apply disabled style to icon children

- packages/docs/src/content/03-components/actions/button/index.mdx
> docs: update index

- packages/docs/src/content/03-components/actions/button/guidelines.mdx
Addition of outline variant + bigger content changes
> docs: update guidelines

- packages/docs/src/content/02-foundations/03-content-guidelines/01-sprach-guide/overview.mdx
moved every headline a size up (e. g. what was h3 is now h2)
> docs: correction headline sizing

- packages/components/src/components/List/components/Items/components/Item/components/OptionsButton/OptionsButton.tsx
Changed Button coloring for the OptionsButton in List items to secondary.
> style: Changed Button coloring for the OptionsButton

- packages/components/src/lib/controller/overlay/OverlayController.ts
- packages/components/src/lib/controller/overlay/useOverlayController.test.ts
- packages/components/src/lib/controller/overlay/useOverlayController.ts
- Simplified handler management in OverlayController
- Removed separate onOpen/onClose properties in favor of unified handler sets
- No functional changes, just internal restructuring
> fix(OverlayController): fix overlayController handler management

- packages/docs/src/content/03-components/form-controls/text-field/overview.mdx
Sorry, I made a mistake in the previous change
> docs: correction

- packages/components/src/components/ColumnLayout/ColumnLayout.tsx
- packages/components/src/components/Icon/components/icons/index.ts
- packages/components/src/integrations/nextjs/components/Link/Link.tsx
- packages/design-tokens/src/structure/column-layout.yml
- packages/docs/src/app/_components/layout/Footer/Footer.tsx
- packages/docs/src/app/_components/layout/Footer/components/FooterSection.module.scss
- packages/docs/src/app/_components/layout/Footer/components/FooterSection.tsx
- packages/docs/src/app/_components/layout/Footer/footer.module.scss
> fix(docs): layout of the footer component

- packages/docs/src/app/_components/layout/Footer/Footer.tsx
> fix(docs): align footer behaviour to new guideline

- apps/docs/src/content/03-components/structure/list/develop.mdx
Resolves https://github.com/mittwald/flow/issues/854
> docs: add List loader docs

- apps/docs/src/content/02-foundations/01-design/02-colors/overview.mdx
- packages/design-tokens/src/color-palette.yml
Closes https://github.com/mittwald/flow/issues/1230
> feat: add categorical colors

- packages/components/src/components/ActionGroup/stories/Default.stories.tsx
- packages/components/src/components/Align/Align.tsx
- packages/components/src/components/Align/stories/InputButton.stories.tsx
- packages/components/src/components/TextField/stories/Default.stories.tsx
- packages/components/src/integrations/react-hook-form/components/ActionGroupWrapper/SubmitButtonStateProvider.tsx
closes https://github.com/mittwald/flow/issues/1252
> feat(Button): support async submit without action

- apps/docs/src/content/03-components/upload/file-card/examples/contextMenu.tsx
- apps/docs/src/content/03-components/upload/file-card/overview.mdx
- packages/components/src/components/FileCard/FileCard.tsx
- packages/components/src/components/FileCard/stories/Default.stories.tsx
> Support ContextMenu in FileCard

- packages/components/src/components/Notification/Notification.tsx
> fix(Notification): Notification interaction should not close Overlay

- packages/remote-react-renderer/src/components.ts
This adds support for the usage of HTML elements necessary for List (`ul`, `ol`, `li`)
> feat(Remote): Support list html elements as remote components

- packages/design-tokens/src/status/progress-bar.yml
> fix(progress-bar): update small size value to use size.s design token

- packages/remote-react-renderer/src/components.ts
closes https://github.com/mittwald/flow/issues/1440
> feat(remote): Allow s (strikethrough) as remote component

- .vscode/settings.json
- apps/docs/src/content/03-components/data-visualisation/area-chart/examples/emptyView.tsx
- apps/docs/src/content/03-components/data-visualisation/area-chart/overview.mdx
- packages/components/package.json
- packages/components/src/components/AreaChart/AreaChart.module.scss
- packages/components/src/components/AreaChart/AreaChart.tsx
- packages/components/src/components/AreaChart/components/Area/Area.tsx
- packages/components/src/components/AreaChart/index.ts
- packages/components/src/components/AreaChart/stories/Default.stories.tsx
- packages/components/src/components/ChartTooltip/ChartTooltip.tsx
- packages/remote-elements/src/auto-generated/RemoteAreaChartElement.ts
- pnpm-lock.yaml
Closes https://github.com/mittwald/flow/issues/1291
> feat(AreaChart): implement emptyView for empty/error display

- apps/remote-dom-demo/src/app/layout.tsx
- apps/remote-dom-demo/src/app/remote/markdown/page.tsx
- packages/components/src/components/Markdown/Markdown.tsx
- packages/components/src/lib/react/cloneElement.ts
- packages/components/src/lib/react/remote.ts
> fix(Markdown): fix not rendering in remote context

- apps/docs/package.json
- apps/docs/src/lib/mdx/components/MdxFileView/customComponents.tsx
- packages/components/src/components/CodeBlock/CodeBlock.tsx
- packages/components/src/components/CopyButton/CopyButton.tsx
- packages/components/src/components/CopyButton/stories/Default.stories.tsx
- packages/remote-elements/src/auto-generated/RemoteCopyButtonElement.ts
- packages/remote-react-components/package.json
- packages/remote-react-components/src/tests/CopyButton.browser.test.remote.tsx
- packages/remote-react-components/src/tests/CopyButton.browser.test.tsx
- pnpm-lock.yaml
> fix(CopyButton): fix not copied to clipboard in remote context

- packages/components/src/components/List/components/Table/components/TableLoadingView.tsx
fixes https://github.com/mittwald/flow/issues/1509
> use view component

- apps/docs/package.json
- packages/components/src/integrations/nextjs/components/RouterProvider/RouterProvider.tsx
- pnpm-lock.yaml
fixes https://github.com/mittwald/flow/issues/1588
> fix(RouterProvider): add basepath to href

- packages/components/src/components/PasswordCreationField/PasswordCreationField.tsx
- packages/components/src/components/PasswordCreationField/stories/Default.stories.tsx
fixes https://github.com/mittwald/flow/issues/1688
> fix(PasswordCreationField): Reset Field on External Change

- apps/docs/src/content/03-components/form-controls/date-picker/guidelines.mdx
> docs: Update DatePicker guidelines.mdx

- packages/components/src/components/Autocomplete/Autocomplete.tsx
Aslong https://github.com/mittwald/flow/pull/1726 is not ready this fixes the close on blur
> Autocomplete fix close on blur

- apps/docs/src/content/03-components/form-controls/password-creation-field/examples/copyButton.tsx
- apps/remote-dom-demo/package.json
- apps/remote-dom-demo/src/app/remote/react-hook-form/page.tsx
- packages/components/src/components/Autocomplete/Autocomplete.tsx
- packages/components/src/components/CopyButton/CopyButton.tsx
- packages/components/src/components/PasswordCreationField/PasswordCreationField.tsx
- packages/components/src/components/PasswordCreationField/stories/Default.stories.tsx
- packages/components/src/components/SearchField/SearchField.tsx
- packages/components/src/components/TextArea/TextArea.tsx
- packages/components/src/lib/promises/useAbortablePromise.ts
- packages/components/src/lib/react/ReactAriaControlledValueFix.tsx
- packages/remote-react-components/src/integrations/react-hook-form/Form/Form.tsx
fixes https://github.com/mittwald/flow/issues/1762
> fix remote input state

- packages/components/src/components/NumberField/NumberField.tsx
- packages/components/src/integrations/react-hook-form/components/Field/stories/NumberField.stories.tsx
fixes https://github.com/mittwald/flow/issues/1812
> Fix Numberfield add correct props location

- apps/docs/src/content/03-components/form-controls/file-field/examples/fieldDescription.tsx
> docs: Update FileField Text fieldDescription.tsx

- apps/docs/src/content/03-components/structure/table/index.mdx
> docs: Update Table index.mdx

- packages/components/src/components/PasswordCreationField/components/PasswordGenerateButton/PasswordGenerateButton.tsx
fixes https://github.com/mittwald/flow/issues/1949
> Don't show success button feedback
